name: osu-sunrise-tests
services:
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - "6339:6379"
    networks:
      - monitoring
        
  postgres:
     image: postgres:latest
     restart: unless-stopped
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: hangfire
     ports:
       - "5433:5432"
     volumes:
       - postgres_data:/var/lib/postgresql/data
     networks:
       - monitoring

volumes:
  redis:
  postgres_data:

networks:
  monitoring:
    driver: bridge