name: osu-sunrise-tests
services:
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - "6339:6379"
    networks:
      - monitoring

volumes:
  redis:
  postgres_data:

networks:
  monitoring:
    driver: bridge