name: osu-sunrise
services:
  sunrise:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./Data:/app/Data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:5147
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificate.pfx
    depends_on:
      - redis
      - prometheus

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3060:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  redis: